# Copyright (C) 2021 Liangyu Wang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Part to build opendlv-pointcloud-preprocessing.
FROM ubuntu:18.04 as builder
ENV DEBIAN_FRONTEND=noninteractive
MAINTAINER Liangyu Wang "liangyu@student.chalmers.se"
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    cmake \
    git \
    build-essential \
    software-properties-common

RUN apt-get update
RUN apt-get install -y libeigen3-dev \
    libflann-dev \
    libboost-all-dev \
    linux-libc-dev \
    libudev-dev \
    mpi-default-dev \
    openmpi-bin \
    openmpi-common \
    libvtk6.3-qt \
    libvtk6.3 \
    libvtk6-dev \
    libqhull* \
    libgtest-dev \
    freeglut3-dev \
    pkg-config \
    libxmu-dev \
    libxi-dev \ 
    mono-complete \
    libqt4-dev \
    openjdk-8-jdk \
    openjdk-8-jre

ADD . /opt/sources
WORKDIR /opt/sources
RUN git clone https://github.com/PointCloudLibrary/pcl.git && \
      cd pcl && \
      git checkout -b 1.8.1 refs/tags/pcl-1.8.1 && \
      mkdir build && cd build && cmake -D CMAKE_INSTALL_PREFIX=/usr/local .. && \
      make -j$(nproc) && make install
