version: "2.3"
services:
    kitti-replay:
        container_name: kitti-replay
        build:
            context: ./opendlv-kitti-replay
            dockerfile: Dockerfile
        image: opendlv-kitti-replay:v0.1
        restart: on-failure
        network_mode: "host"
        ipc: "host"
        volumes:
        - ${HOME}/Learning_PCL/Test_data/2011_09_26_drive_0009_sync:/opt/recordings
        - /tmp:/tmp
        network_mode: "host"
        command: "--cid=111 --freq=10 --name=123.pcd /opt/recordings/ --verbose --id-sender=100"
    
    pointcloud_processing:
        container_name: pointcloud_processing
        build:
            context: ./opendlv-pointcloud-preprocessing
            dockerfile: Dockerfile
        image: opendlv-pointcloud-preprocessing:v0.1
        runtime: nvidia
        ipc: "host"
        network_mode: "host"
        environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - DISPLAY=${DISPLAY}
        #depends_on:
        #- "kitti-replay"
        volumes:
        - /tmp:/tmp
        command: "--cid=111 --freq=40 --name_read=123.pcd --name_send=234.pcd --display --verbose"

    unscented-kalman-filter:
        container_name: unscented-kalman-filter
        build:
            context: ./opendlv-unscented-kalman-filter
            dockerfile: Dockerfile
        image: opendlv-unscented-kalman-filter:v0.1
        ipc: "host"
        network_mode: "host"
        depends_on:
        - "kitti-replay"
        command: "--cid=111 --freq=10 --imu-freq=10 --gps-freq=10 --display --verbose"

    #pointcloud_registration:
    #    container_name: pointcloud_registration
    #    build:
    #        context: ./opendlv-pointcloud-registration
    #        dockerfile: Dockerfile
    #    image: opendlv-pointcloud-registration:v0.1
    #    runtime: nvidia
    #    ipc: "host"
    #    network_mode: "host"
    #    environment:
    #    - NVIDIA_VISIBLE_DEVICES=all
    #    - DISPLAY=${DISPLAY}
    #    #depends_on:
    #    #- "pointcloud_processing"
    #    volumes:
    #    - /tmp:/tmp
    #    command: "--cid=111 --freq=10 --name_processed=234.pcd --display --verbose"

    map-plotter:
        container_name: map-plotter
        build:
            context: ./opendlv-map-plotter
            dockerfile: Dockerfile
        image: opendlv-map-plotter:v0.1
        network_mode: "host"
        environment:
        - DISPLAY=${DISPLAY}
        depends_on: 
        - "unscented-kalman-filter"
        command: "--cid=111 --freq=1 "