# This is a basic workflow to help you get started with Actions

name: Docker Builds

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}} 
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}    
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
        
      - name: docker build 'Kitti Replay'
        run: docker build ./opendlv-kitti-replay -t leowang1997/opendlv-kitti-replay:v0.1
          
      - name: docker build 'Unscented Kalman Filter'
        run: docker build ./opendlv-unscented-kalman-filter -t leowang1997/opendlv-unscented-kalman-filter:v0.1
          
      - name: docker build 'Map Plotter'
        run: docker build ./opendlv-map-plotter -t leowang1997/opendlv-map-plotter:v0.1
          
      - name: push images to Docker Hub
        run: |
          docker push leowang1997/opendlv-kitti-replay:v0.1
          docker push leowang1997/opendlv-unscented-kalman-filter:v0.1
          docker push leowang1997/opendlv-map-plotter:v0.1
        

